name: CI

on: [push, pull_request]

jobs:

  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v5

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install pcsclite
        run: sudo apt-get install -y libpcsclite1 libpcsclite-dev pcscd
        if: matrix.os == 'ubuntu-latest'

      - name: Install dependencies
        run: yarn install --verbose

      - name: Run tests
        run: yarn test

      - name: Build dist
        run: yarn build
