name: Continous Integration

on:
  pull_request:
    branches:
      - main

jobs:

  Build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [18, 20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y build-essential python3

      - name: Install pcsclite on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y libpcsclite1 libpcsclite-dev pcscd

      # Automatically runs `node-gyp rebuild``
      # https://docs.npmjs.com/cli/v7/configuring-npm/package-json#default-values
      # If there is a binding.gyp file in the root of your package and you have
      # not defined an install or preinstall script, npm will default the install
      # command to compile using node-gyp.
      - name: Install dependencies
        run: yarn install

      # Currently running tests only on MacOS
      - name: Run lib tests
        if: matrix.os == 'macos-latest'
        run: yarn test

      - name: Compile code
        run: yarn compile
