name: Continous Integration

on: [push, pull_request]

jobs:

  Build:
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 20, 22]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install pcsclite
        run: sudo apt-get install -y libpcsclite1 libpcsclite-dev pcscd
        if: matrix.os == 'ubuntu-latest'

      - name: Install lib dependencies
        run: yarn --cwd ./lib install --verbose

      - name: Run lib tests
        run: yarn --cwd ./lib test

      - name: Build lib
        run: yarn --cwd ./lib build

      - name: Install package dependencies
        run: yarn install --verbose

      - name: Run package tests
        run: yarn test

      - name: Build package
        run: yarn build
